/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class ElfBinary {
  constructor(path: string)
  /** Add a DT_NEEDED shared library entry. */
  addLibrary(name: string): void
  /** Write the (modified) binary to the given output path. */
  write(outputPath: string): void
}
